---
- name: this playbook installs apache w.r.t to os family
  hosts: 
         webservers
         dbservers
         appservers
  become: yes
  tasks:
  - name: install apache2 pkg
    apt: 
      name: apache2
      state: present
    when: ansible_os_family == "Debian"

  - name: reStart apache2 service
    service:
      name: apache2
      state: restarted
    when: ansible_os_family == "Debian"

  - name: install httpd pkg
    yum:
      name: httpd
      state: present
    when: ansible_os_family == "RedHat"

  - name: restart httpd service
    service:
      name: httpd
      state: restarted
    when: ansible_os_family == "RedHat"
