---
- name: creates  multi users
  hosts: all
  become: yes
  tasks:
  - name: creates a user {{user}}
    user: 
      name: '{{ item }}'
      state: present
    with_items:
    - sravan
    - manu
    - rpr
    - user11
    - user12
