---
- name: setting up tomcat service
  hosts: all
  become: yes
  tasks:
  - name: install java on ubuntu
    apt:
      name: default-jre
      state: present
    when: ansible_os_family == "Debian"

  - name: install java on redhat
    yum:
      name: java
      state: present
    when: ansible_os_family == "RedHat"

  - name: download tomcat
    get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.8/bin/apache-tomcat-10.1.8.tar.gz
      dest: /opt

  - name: extract tomcat
    unarchive:
      src: /opt/apache-tomcat-10.1.8.tar.gz
      dest: /opt
      remote_src: yes

  - name: adding executing permissions
    file:
      path: /opt/apache-tomcat-10.1.8/bin/startup.sh
      mode: 0777

  - name: running shell script
    shell: nohup ./startup.sh
    args:
      chdir: /opt/apache-tomcat-10.1.8/bin
