---
- name: this playbook removes apache2 
  hosts: all
  become: yes
  tasks: 
  - name: stop apache2
    service:
      name: apache2
      state: stopped
    when: ansible_os_family == "Debian"

  - name: stop httpd
    service:
      name: httpd
      state: stopped
    when: ansible_os_family == "RedHat"

  - name: remove apache2
    apt:
      name: apache2
      state: absent
    when: ansible_os_family == "Debian"

  - name: remove httpd
    yum:
      name: httpd
      state: absent
    when: ansible_os_family == "RedHat"

