---
# tasks file for apache2-httpd-role.yml

- name: install apache2 pkg
  apt:
    name: apache2
    state: present
  when: ansible_os_family == "Debian"
  notify: restart apache2 service

- name: install httpd pkg
  yum:
    name: httpd
    state: present
  when: ansible_os_family == "RedHat"
  notify: restart httpd service

- name: coping index file
  copy:
    src: /home/ansadmin/index.html
    dest: /var/www/html
    mode: 0777


